<?php
/**
 * Request System
 *
 * CheckRequest.php genterates a check request form.
 *
 * @version 1.5
 * @link http://www.yourdomain.com/go/Request/
 * @author	Thomas LeZotte (tom@lezotte.net)
 *
 * @package PO
  * @filesource
 *
 * PHP Debug
 * @link http://phpdebug.sourceforge.net/
 */
 
/**
 * - Start Page Loading Timer
 */
include_once('../include/Timer.php');
$starttime = StartLoadTimer();
/**
 * - Set debug mode
 */
$debug_page = false;
include_once('debug/header.php');


/**
 * - Database Connection
 */
require_once('../Connections/connDB.php');
/**
 * - Config Information
 */
require_once('../include/config.php'); 
/**
 * - Check User Access
 */
require_once('../security/check_user.php');


/* Update Summary */
Summary($dbh, 'Check Request', $_SESSION['eid']);

/* ------------------ START DATABASE CONNECTIONS ----------------------- */
/* Getting PO information */
$PO = $dbh->getRow("SELECT * 
				    FROM PO 
				    WHERE id = ?",array($_POST['id']));
/* Get Employee names from Standards database */
$EMPLOYEES = $dbh->getAssoc("SELECT eid, CONCAT(fst,' ',lst) AS name 
						     FROM Standards.Employees");
/* Getting plant locations from Standards.Plants */								
$PLANT = $dbh->getRow("SELECT id, name 
                       FROM Standards.Plants 
					   WHERE id = ?",array($_POST['plant']));
/* Getting companies from Standards.Companies */								
$COMPANY = $dbh->getRow("SELECT id, name 
						 FROM Standards.Companies 
					     WHERE id = ?",array($_POST['company']));
/* Getting suppliers from Suppliers */						 
$SUPPLIER = $dbh->getRow("SELECT BTVEND AS id, BTNAME AS name, BTSTAT AS status
							FROM Standards.Vendor
						  WHERE BTVEND = ?",array($_POST['supplier']));				   					 	
/* ------------------ END DATABASE CONNECTIONS ----------------------- */



/* ------------- START PROCESSING --------------------- */
require('fpdf/fpdf.php');


class PDF extends FPDF
{
function Header()
{
	/* Select company logo */
	switch ($_POST['company']) {
		case 1:
				$logo = 'Company';
				break;
		case 2:
				$logo = 'Deluxe';
				break;
		default:
				$logo = 'Company';
				break;
	}
	$this->SetY(20);
	$this->Image('http://www.yourdomain.com/Common/images/'.$logo.'.jpg',7,15);	//Print Logo
	$this->SetFont('Arial','B',14);		//Set Font: Type, Size
	$this->SetX(120);					//Move to the right
	$this->Cell(0,10,'Check Request');	//Print Title
}

function Footer()
{
	global $default;

	$this->SetY(-20);		//Position at 1.5 cm from bottom
	$this->SetFont('Arial','I',8);
	$this->SetX(140);
	$this->Cell(0,5,'Generated by Your Company '.$default['title1'],0,1);
}
}

//Instanciation of inherited class
$pdf=new PDF();


/* ------------- START PDF --------------------- */
$pdf->AddPage();												//Start Page
$pdf->SetFont('Arial','',12);
$pdf->SetY(40);													//Move below Logo
$pdf->Cell(90,7,'Plant: '.$PLANT['name']);
$pdf->Cell(90,7,'Today\'s Date: '.date("F j, Y"),0,1);
$pdf->Cell(90,7,'Vendor Code: ');	
$pdf->Cell(90,7,'Date for FedEx: '.date("F j, Y",strtotime($_POST['fedexDate'])),0,1);	
$pdf->Cell(90,7,'Vendor Name: '.ucwords(strtolower($SUPPLIER['name'])));
$pdf->SetFont('Arial','B',12);
$pdf->Cell(90,7,'FedEx Address',0,1);
$pdf->SetFont('Arial','',12);
$pdf->Cell(90,7,'');
$pdf->Cell(90,7,' Company Name:  '.ucwords(strtolower($SUPPLIER['name'])),0,1);	
$pdf->Cell(90,7,'');	
$pdf->Cell(90,7,' Street Address:    '.ucwords(strtolower($SUPPLIER['address'])),0,1);	
$pdf->Cell(90,7,'Amount of Request: $'.number_format($_POST['total'], 2, '.', ''));	
$pdf->Cell(90,7,' City, State ZIP:     '.ucwords(strtolower($SUPPLIER['city'])).", ".strtoupper($SUPPLIER['state'])." ".$SUPPLIER['zip5'],0,1);						//Line 1
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
/* ---- Start of Reason for Request Section ---- */
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,7,'Reason for Request',0,1);
$pdf->SetFont('Arial','',12);

$one = ($_POST['reason'] == '1') ? 'X' : '';
$pdf->Cell(10,7,$one,1);									//Display X if this option was selected
$pdf->Cell(100,7,'Vendor requires payment in advance',0,1);

$two = ($_POST['reason'] == '2') ? 'X' : '';
$pdf->Cell(10,7,$two,1);									//Display X if this option was selected
$pdf->Cell(100,7,'Vendor requires Old Invoices to be paid',0,1);	
$pdf->SetX(20);
$pdf->SetFont('Arial','U',12);
$pdf->Cell(50,7,'Invoice');
$pdf->Cell(50,7,'Amount',0,1);
$pdf->SetFont('Arial','',12);
$pdf->SetX(20);
$pdf->Cell(50,7,$_POST['inv1']);
$pdf->Cell(50,7,'$'.number_format($_POST['amt1'], 2, '.', ''),0,1);
$pdf->SetX(20);
$pdf->Cell(50,7,$_POST['inv2']);
$pdf->Cell(50,7,'$'.number_format($_POST['amt2'], 2, '.', ''),0,1);
$pdf->SetX(20);
$pdf->Cell(50,7,$_POST['inv3']);
$pdf->Cell(50,7,'$'.number_format($_POST['amt3'], 2, '.', ''),0,1);
$pdf->SetX(20);
$pdf->Cell(50,7,$_POST['inv4']);
$pdf->Cell(50,7,'$'.number_format($_POST['amt4'], 2, '.', ''),0,1);
$pdf->SetX(20);
$pdf->Cell(50,7,$_POST['inv5']);
$pdf->Cell(50,7,'$'.number_format($_POST['amt5'], 2, '.', ''),0,1);
$pdf->SetX(20);
$pdf->Cell(50,7,$_POST['inv6']);
$pdf->Cell(50,7,'$'.number_format($_POST['amt6'], 2, '.', ''),0,1);
$pdf->SetX(20);
$pdf->Cell(50,7,$_POST['inv7']);
$pdf->Cell(50,7,'$'.number_format($_POST['amt7'], 2, '.', ''),0,1);

$three = ($_POST['reason'] == '3') ? 'X' : '';
$pdf->Cell(10,7,$three,1);									//Display X if this option was selected
$pdf->Cell(100,7,'Vendor requires a Held Check to be released',0,1);

$four = ($_POST['reason'] == '4') ? 'X' : '';				//Display X if this option was selected
$pdf->Cell(10,7,$four,1);	
$pdf->Cell(100,7,'Other  Acct# 06-01-10-0131-00',0,1);
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
/* ---- Start of Authorization Section ---- */
$pdf->Cell(100,7,'Requested By: '.ucwords(strtolower($EMPLOYEES[$PO[req]])));
$pdf->Cell(100,7,'Date: '.date("F j, Y"),0,1);
$pdf->Cell(100,7,'Controller: '.ucwords(strtolower($EMPLOYEES[$_POST['controller']])));
$pdf->Cell(100,7,'Date: '.date("F j, Y"),0,1);

/* Only display signature when PO is Approved, Ordered or Received */
if ($PO['status'] == 'A' or $PO['status'] == 'O' or $PO['status'] == 'R') {
	$signature_image = $default['FS_HOME'].$default['signatures']."/".$_POST['controller'].".jpg";		// Set images filesystem location
	$signature_web = $default['URL_HOME'].$default['signatures']."/".$_POST['controller'].".jpg";		// Set images URL location 

	/* Determin if a signature image exists */
	if (file_exists($signature_image)) {
		$pdf->Image($signature_web,30,240);				//Display signature image
	} else {
		/* ---- Start of Signature Watermark Section ---- */
		$pdf->SetTextColor(235,235,235);		//Set text color light gray
		$pdf->SetFont('Arial','B',24);
		$pdf->SetX(40);
		$pdf->Cell(0,10,'SIGNATURE');	//Display text signature
	}
}

/* ---- Set output preference ---- */
$output = ($_GET['output'] == 'save') ? 'D' : 'I';
$pdf->Output('CompanyReferences.pdf',$output);
/* ------------- END PDF --------------------- */

/**
 * - Display Debug Information
 */
include_once('debug/footer.php');
/**
 * - Disconnect from database
 */
$dbh->disconnect();
?>